image:
  # repository: ghcr.io/<GITHUB_OWNER>/api-fastapi
  # tag: "dev"
  repository: ghcr.io/jinsoooooooo/template-fastapi
  tag: "latest"
  pullPolicy: Always

service:
  port: 80
  targetPort: 8080
