apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_NAME: "{{ .Values.env.APP_NAME }}"
  APP_HOST: "{{ .Values.env.APP_HOST }}"
  APP_PORT: "{{ .Values.env.APP_PORT }}"
  APP_LOG_LEVEL: "{{ .Values.env.APP_LOG_LEVEL }}"