apiVersion: v1
kind: Service
metadata:
  name: api-fastapi
spec:
  selector:
    app: api-fastapi
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
